### ISSUE TITLE
fix directory on s3

### ISSUE THREAD

**Issue by eroux** [OpenPecha/OCR-Pipelines#9]
From what I see in https://github.com/OpenPecha/OCR-Pipelines/blob/main/ocr_pipelines/upload.py the s3 prefix is wrong, it should be like

```
s3://ocr.bdrc.io/Works/05/W1PD289/{service}/{batch}/
```

with `{service}` = `vision` for Google Vision, and `{batch}` being a unique identifier for the ocr batch of a specific work.

**Comment by 10zinten** [comment]
@eroux can you review my [PR](https://github.com/OpenPecha/OCR-Pipelines/pull/13) for this.

**Comment by 10zinten** [comment]
@eroux since, our [old script](https://github.com/OpenPecha/OCR-Helper-Scripts/blob/master/usage/bdrc/bdrc_ocr.py#L337-L367) uploads both ocr output and images to `s3://ocr.bdrc.io`, should we do the same here?

the directory for
- images was `s3://ocr.bdrc.io/Works/05/W1PD289/{service}/{batch}/images`
- ocr outputs was `s3://ocr.bdrc.io/Works/05/W1PD289/{service}/{batch}/ocr_outputs`

**Comment by eroux** [comment]
Looking at a random place on s3, I see the ocr output in `output/` not `ocr_outputs/`, as in `s3://ocr.bdrc.io/Works/02/W1EE36/vision/batch001/output/`, so let's keep it that way

**Comment by eroux** [comment]
but yes, we should absolutely keep the exact same file organization, I can't think of any reason to change it
